#!/bin/bash

exec 3>&1 1>>"$LOG_DIR/orangehrm_backup.log" 2>&1
set -x
set -e

if [[ -z  $OHRM_DIR ]]; then
    printf "\nPlease run this script from the OrangeHRM command\n" >&3
    printf "i.e. orangehrm backup\n\n" >&3
    exit 1;
fi

# Function to run backup scripts.
# Give the name of the script as the first argument
ohrm_backup_script() {
    sh "$BACKUP_SCRIPTS_DIR/$1" >&3
}

# Pass the name of the log file as the first argument
# shellcheck disable=SC2317
err_exit() {
    printf "\n%bSomething has gone wrong!%b\n" "$RC" "$EC" >&3
    cp -rf "$LOG_DIR/$1" "$HOME"
    printf "Please find the relevant long files at %b%s%b\n\n" "$GC" "$HOME/$1" "$EC" >&3
    exit 1
}

if [[ $# -eq 0 ]]; then
    # If no arguments
    ohrm_backup_script backup_help
else
    case $1 in
        help)
            ohrm_backup_script backup_help
            ;;
        create)
            trap 'err_exit orangehrm_backup_create.log' ERR
            ohrm_backup_script create
            ;;
        restore)
            trap 'err_exit orangehrm_backup_restore.log' ERR
            ohrm_backup_script restore
            ;;
        list)
            trap 'err_exit orangehrm_backup_list.log' ERR
            ohrm_backup_script list
            ;;
        clean)
            trap 'err_exit orangehrm_backup_clean.log' ERR
            ohrm_backup_script clean
            ;;
        *)
            printf "\n%b%s%b is not an orangehrm backup commmand" "$RC" "$1" "$EC" >&3
            printf "See '%borangehrm backup help%b'\n\n" "$GC" "$EC" >&3
            ;;
    esac
fi
